// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notificationSys.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_notificationSys_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_notificationSys_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_notificationSys_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_notificationSys_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
namespace mifan {
class noteActiveUser;
class noteActiveUserDefaultTypeInternal;
extern noteActiveUserDefaultTypeInternal _noteActiveUser_default_instance_;
}  // namespace mifan
PROTOBUF_NAMESPACE_OPEN
template<> ::mifan::noteActiveUser* Arena::CreateMaybeMessage<::mifan::noteActiveUser>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mifan {

// ===================================================================

class noteActiveUser :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:mifan.noteActiveUser) */ {
 public:
  noteActiveUser();
  virtual ~noteActiveUser();

  noteActiveUser(const noteActiveUser& from);
  noteActiveUser(noteActiveUser&& from) noexcept
    : noteActiveUser() {
    *this = ::std::move(from);
  }

  inline noteActiveUser& operator=(const noteActiveUser& from) {
    CopyFrom(from);
    return *this;
  }
  inline noteActiveUser& operator=(noteActiveUser&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const noteActiveUser& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const noteActiveUser* internal_default_instance() {
    return reinterpret_cast<const noteActiveUser*>(
               &_noteActiveUser_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(noteActiveUser* other);
  friend void swap(noteActiveUser& a, noteActiveUser& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline noteActiveUser* New() const final {
    return CreateMaybeMessage<noteActiveUser>(nullptr);
  }

  noteActiveUser* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<noteActiveUser>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const noteActiveUser& from);
  void MergeFrom(const noteActiveUser& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(noteActiveUser* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mifan.noteActiveUser";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 userid = 1;
  void clear_userid();
  static const int kUseridFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::int32 userid() const;
  void set_userid(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 time = 2;
  void clear_time();
  static const int kTimeFieldNumber = 2;
  ::PROTOBUF_NAMESPACE_ID::int32 time() const;
  void set_time(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:mifan.noteActiveUser)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int32 userid_;
  ::PROTOBUF_NAMESPACE_ID::int32 time_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_notificationSys_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// noteActiveUser

// int32 userid = 1;
inline void noteActiveUser::clear_userid() {
  userid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 noteActiveUser::userid() const {
  // @@protoc_insertion_point(field_get:mifan.noteActiveUser.userid)
  return userid_;
}
inline void noteActiveUser::set_userid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  userid_ = value;
  // @@protoc_insertion_point(field_set:mifan.noteActiveUser.userid)
}

// int32 time = 2;
inline void noteActiveUser::clear_time() {
  time_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 noteActiveUser::time() const {
  // @@protoc_insertion_point(field_get:mifan.noteActiveUser.time)
  return time_;
}
inline void noteActiveUser::set_time(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  time_ = value;
  // @@protoc_insertion_point(field_set:mifan.noteActiveUser.time)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace mifan

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_notificationSys_2eproto
